services:
  db:
    image: postgres:15-alpine   # <-- было 16.x
    environment:
      POSTGRES_DB: trainer_db
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: trainer
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: sportapp_minio
    # S3-совместимое объектное хранилище для фото профилей
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    container_name: trainer_backend
    environment:
      # Эти переменные подхватит Spring
      DB_URL: jdbc:postgresql://db:5432/trainer_db
      DB_USER: trainer
      DB_PASS: trainer
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: profile-photos
      # переменная для доступа к внешнему погодному API.
      # Значение подставляется из переменных окружения хоста (если задано).
      # Пример: в PowerShell `$env:OPENWEATHERMAP_API_KEY="ваш_ключ"` перед `docker compose up`.
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY:-}
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: trainer_frontend
    depends_on:
      - backend
    ports:
      - "5173:80" # сайт будет на http://localhost:5173

volumes:
  pg_data:
  minio_data:
